version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing .NET Core
      - dotnet --version # Check the installed version of .NET Core
      - echo Restoring dependencies...
      - dotnet restore aqa.csproj # Restore dependencies for the project
  pre_build:
    commands:
      - echo Starting pre-build phase...
      - echo Restoring NuGet packages...
      - dotnet restore # Restore the .NET packages for the solution
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release # Build the solution in Release mode
  post_build:
    commands:
      - echo Running tests...
      - dotnet test --no-build --verbosity normal # Run unit tests
artifacts:
  files:
    - '**/bin/Release/net6.0/publish/**'
  discard-paths: yes
