version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Restoring .NET project dependencies..."
      - dotnet restore aqa.csproj
  build:
    commands:
      - echo "Publishing the project..."
      - dotnet publish aqa.csproj --configuration Release
  post_build:
    commands:
      - echo "Running tests..."
      - dotnet test --no-build --verbosity normal
artifacts:
  files:
    - 'bin/Release/net8.0/publish/**' # Use the default output directory for published files
  discard-paths: yes
