version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0 # Install .NET SDK version 8.0
    commands:
      - echo Installing .NET SDK...
      - dotnet restore aqa.csproj # Restore the project's dependencies
  build:
    commands:
      - echo Building the project...
      - dotnet build aqa.csproj --configuration Release # Build the project explicitly
  post_build:
    commands:
      - echo Running tests...
      - dotnet test aqa.csproj --no-build --verbosity normal # Run the tests for the specific project
artifacts:
  files:
    - 'publish/**' # Collect all files from the 'publish' folder
  base-directory: publish # Specify the base directory where artifacts are located
