version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0 # Install .NET SDK version 8.0
    commands:
      - echo "Restoring .NET project dependencies..."
      - dotnet restore aqa.csproj # Restore project dependencies
  build:
    commands:
      - echo "Publishing the project..."
      - dotnet publish aqa.csproj --configuration Release --output ./publish # Publish the project to ./publish
  post_build:
    commands:
      - echo "Running tests..."
      - dotnet test --no-build --verbosity normal # Run tests (optional)
artifacts:
  files:
    - 'publish/' # Collect all files from the publish directory
  discard-paths: yes
